-- AlterTable
ALTER TABLE "User" ALTER COLUMN "celular" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "cnpj" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "cpf" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "tel_fixo" SET DATA TYPE VARCHAR(20);
